"""add clerk_user_id column

Revision ID: 1f043947528f
Revises: 641687878e90
Create Date: 2026-04-27 12:01:50.615456

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f043947528f'
down_revision: Union[str, Sequence[str], None] = '641687878e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.String(length=255), nullable=False, comment='Clerk user ID e.g. user_2abc... — the auth identity'))
    op.create_index('ix_users_clerk_user_id', 'users', ['clerk_user_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['clerk_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_clerk_user_id', table_name='users')
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###
