"""initial tables

Revision ID: 641687878e90
Revises: 
Create Date: 2026-04-19 16:53:15.919082

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '641687878e90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('landlords',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('paybill_number', sa.String(length=20), nullable=False, comment='Safaricom Paybill - unique per landlord'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paybill_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_landlords_paybill', 'landlords', ['paybill_number'], unique=True)
    op.create_index('ix_landlords_phone', 'landlords', ['phone'], unique=False)
    op.create_index('ix_landlords_user_id', 'landlords', ['user_id'], unique=False)
    op.create_table('buildings',
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='Short code used in MPESA account reference e.g PALM'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landlord_id', 'code', name='uq_buildings_landlord_code')
    )
    op.create_index('ix_buildings_landlord_id', 'buildings', ['landlord_id'], unique=False)
    op.create_table('tenants',
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('national_id', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landlord_id', 'national_id', name='uq_tenants_landlord_national_id')
    )
    op.create_index('ix_tenants_landlord_id', 'tenants', ['landlord_id'], unique=False)
    op.create_index('ix_tenants_national_id', 'tenants', ['national_id'], unique=False)
    op.create_index('ix_tenants_phone', 'tenants', ['phone'], unique=False)
    op.create_table('building_charge_configs',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('garbage_charge', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('water_rate_per_unit', sa.Numeric(precision=19, scale=4), nullable=False, comment='KES per cubic metre consumed'),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_building_charge_configs_building_id', 'building_charge_configs', ['building_id'], unique=False)
    op.create_index('ix_building_charge_configs_effective', 'building_charge_configs', ['building_id', 'effective_from'], unique=False)
    op.create_table('units',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=False, comment='e.g A1,B1 - unique within building'),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('rent_amount', sa.Numeric(precision=19, scale=4), nullable=False, comment='Current listed rent - may differ from lease.rent_amount (snapshot)'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'unit_number', name='uq_units_building_number')
    )
    op.create_index('ix_units_building_id', 'units', ['building_id'], unique=False)
    op.create_index('ix_units_building_status', 'units', ['building_id', 'status'], unique=False)
    op.create_table('leases',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=19, scale=4), nullable=False, comment='Snapshot of unit.rent_amount at lease signing'),
    sa.Column('deposit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('deposit_status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Null = month-to-month'),
    sa.Column('account_reference', sa.String(length=30), nullable=False, comment='M-PESA account reference e.g PALM-A3 '),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_reference')
    )
    op.create_index('ix_leases_account_reference', 'leases', ['account_reference'], unique=True)
    op.create_index('ix_leases_tenant_id', 'leases', ['tenant_id'], unique=False)
    op.create_index('ix_leases_unit_id', 'leases', ['unit_id'], unique=False)
    op.create_index('ix_leases_unit_status', 'leases', ['unit_id', 'status'], unique=False)
    op.create_index('uq_leases_one_active_per_unit', 'leases', ['unit_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('mpesa_payments',
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('mpesa_receipt_number', sa.String(length=30), nullable=False),
    sa.Column('business_short_code', sa.String(length=20), nullable=False),
    sa.Column('account_reference', sa.String(length=30), nullable=False),
    sa.Column('msisdn', sa.String(length=15), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matched_lease_id', sa.UUID(), nullable=True),
    sa.Column('matched_period', sa.String(length=7), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['matched_lease_id'], ['leases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_receipt_number'),
    sa.UniqueConstraint('mpesa_receipt_number', name='uq_mpesa_receipt')
    )
    op.create_index('ix_mpesa_payments_landlord_created', 'mpesa_payments', ['landlord_id', 'created_at'], unique=False)
    op.create_index('ix_mpesa_payments_landlord_id', 'mpesa_payments', ['landlord_id'], unique=False)
    op.create_index('ix_mpesa_payments_landlord_reconciled', 'mpesa_payments', ['landlord_id', 'is_reconciled'], unique=False)
    op.create_table('notification_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_logs_lease_period', 'notification_logs', ['lease_id', 'period', 'type'], unique=False)
    op.create_index('ix_notification_logs_sent_at', 'notification_logs', ['sent_at'], unique=False)
    op.create_index('ix_notification_logs_tenant_id', 'notification_logs', ['tenant_id'], unique=False)
    op.create_table('water_readings',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('previous_reading', sa.Numeric(precision=19, scale=4), nullable=False, comment='Auto-populated from last period current_reading'),
    sa.Column('current_reading', sa.Numeric(precision=19, scale=4), nullable=False, comment='Entered by landlord'),
    sa.Column('units_consumed', sa.Numeric(precision=19, scale=4), nullable=False, comment='current_reading - previous_reading'),
    sa.Column('rate_per_unit', sa.Numeric(precision=19, scale=4), nullable=False, comment='Snapshot of building_charge_configs.water_rate_per_unit'),
    sa.Column('water_charge', sa.Numeric(precision=19, scale=4), nullable=False, comment='units_consumed * rate_per_unit'),
    sa.Column('entered_by', sa.UUID(), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'period', name='uq_water_readings_unit_period')
    )
    op.create_index('ix_water_readings_lease_id', 'water_readings', ['lease_id'], unique=False)
    op.create_index('ix_water_readings_unit_id', 'water_readings', ['unit_id'], unique=False)
    op.create_table('rent_ledger',
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False, comment='YYYY_MM e.g 2025-01'),
    sa.Column('base_rent', sa.Numeric(precision=19, scale=4), nullable=False, comment='Snapshot from lease.rent_amount'),
    sa.Column('water_charge', sa.Numeric(precision=19, scale=4), nullable=False, comment='0 until landlord enters the water reading'),
    sa.Column('garbage_charge', sa.Numeric(precision=19, scale=4), nullable=False, comment='Snapshot from building_charge_configs'),
    sa.Column('previous_balance', sa.Numeric(precision=19, scale=4), nullable=False, comment='Carry forward from prior period (positive = owes)'),
    sa.Column('total_amount_due', sa.Numeric(precision=19, scale=4), nullable=False, comment='base_rent + water_charge + garbage_charge + previous_balance'),
    sa.Column('amount_paid', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=4), nullable=False, comment='total_amount_due - amount_paid (positive = still owes)'),
    sa.Column('water_reading_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['water_reading_id'], ['water_readings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lease_id', 'period', name='uq_rent_ledger_lease_period')
    )
    op.create_index('ix_rent_ledger_lease_id', 'rent_ledger', ['lease_id'], unique=False)
    op.create_index('ix_rent_ledger_period_status', 'rent_ledger', ['period', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rent_ledger_period_status', table_name='rent_ledger')
    op.drop_index('ix_rent_ledger_lease_id', table_name='rent_ledger')
    op.drop_table('rent_ledger')
    op.drop_index('ix_water_readings_unit_id', table_name='water_readings')
    op.drop_index('ix_water_readings_lease_id', table_name='water_readings')
    op.drop_table('water_readings')
    op.drop_index('ix_notification_logs_tenant_id', table_name='notification_logs')
    op.drop_index('ix_notification_logs_sent_at', table_name='notification_logs')
    op.drop_index('ix_notification_logs_lease_period', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('ix_mpesa_payments_landlord_reconciled', table_name='mpesa_payments')
    op.drop_index('ix_mpesa_payments_landlord_id', table_name='mpesa_payments')
    op.drop_index('ix_mpesa_payments_landlord_created', table_name='mpesa_payments')
    op.drop_table('mpesa_payments')
    op.drop_index('uq_leases_one_active_per_unit', table_name='leases', postgresql_where="status = 'active'")
    op.drop_index('ix_leases_unit_status', table_name='leases')
    op.drop_index('ix_leases_unit_id', table_name='leases')
    op.drop_index('ix_leases_tenant_id', table_name='leases')
    op.drop_index('ix_leases_account_reference', table_name='leases')
    op.drop_table('leases')
    op.drop_index('ix_units_building_status', table_name='units')
    op.drop_index('ix_units_building_id', table_name='units')
    op.drop_table('units')
    op.drop_index('ix_building_charge_configs_effective', table_name='building_charge_configs')
    op.drop_index('ix_building_charge_configs_building_id', table_name='building_charge_configs')
    op.drop_table('building_charge_configs')
    op.drop_index('ix_tenants_phone', table_name='tenants')
    op.drop_index('ix_tenants_national_id', table_name='tenants')
    op.drop_index('ix_tenants_landlord_id', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_buildings_landlord_id', table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('ix_landlords_user_id', table_name='landlords')
    op.drop_index('ix_landlords_phone', table_name='landlords')
    op.drop_index('ix_landlords_paybill', table_name='landlords')
    op.drop_table('landlords')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
