"""Pydantic v2 schemas
Strict validation on all inputs.
"""

from datetime import date, datetime
from decimal import Decimal
from typing import Any
import uuid
from pydantic import BaseModel, EmailStr, Field, field_validator, model_validator

from nyumbapay_core.app.models.enums import UserRole

"""Not required since clerk owns the entire auth flow"""
# Auth
# class LoginRequest(BaseModel):
#     email: EmailStr
#     password: str = Field(min_length=8)


# class TokenResponse(BaseModel):
#     access_token: str
#     refresh_token: str
#     token_type: str = "bearer"
#     expires_in: int  # seconds


# class RefreshRequest(BaseModel):
#     refresh_token: str


# class AccessTokenResponse(BaseModel):
#     access_token: str
#     token_type: str = "bearer"
#     expires_in: int


# user
class UserResponse(BaseModel):
    id: uuid.UUID
    clerk_user_id: str
    email: str
    role: UserRole
    is_active: bool
    created_at: datetime

    model_config = {"from_attributes": True}


# landlord
class CreateLandlordRequest(BaseModel):
    """Super-admin payload to onbord a new landlord"""

    # user credentials
    email: EmailStr
    # password: str = Field(
    #     min_length=12,
    #     description="Min 12 chars — generated by super-admin, shared securely",
    # )
    # landlord profile
    full_name: str = Field(min_length=2, max_length=255)
    phone: str = Field(min_length=10, max_length=20, pattern=r"^\+?[\d\s\-]+$")
    business_name: str = Field(min_length=2, max_length=255)

    # daraja
    paybill_number: str = Field(
        min_length=5,
        max_length=20,
        pattern=r"^\d+$",
        description="Safaricom Paybill short code — digits only",
    )
    daraja_consumer_key: str = Field(
        min_length=10, description="From Safaricom Daraja app"
    )
    daraja_consumer_secret: str = Field(
        min_length=10, description="From Safaricom Daraja app"
    )
    daraja_environment: str = Field(
        default="production",
        pattern=r"^(production|sandbox)$",
    )

    @field_validator("phone")
    @classmethod
    def normalise_phone(cls, v: str) -> str:
        """Strip spaces and dashes.Normalise 07XX to 2547XX"""
        v = v.strip().replace(" ", "").replace("-", "").replace("+", "")
        if v.startswith("0") and len(v) == 10:
            v = "254" + v[1:]
        return v


class LandlordResponse(BaseModel):
    id: uuid.UUID
    user_id: uuid.UUID
    full_name: str
    phone: str
    business_name: str
    paybill_number: str
    is_active: bool
    c2b_registered: bool
    created_at: datetime

    model_config = {"from_attributes": True}


class LandlordListResponse(BaseModel):
    items: list[LandlordResponse]
    total: int
    page: int
    page_size: int


class UpdateLandlordRequest(BaseModel):
    full_name: str | None = Field(None, min_length=2, max_length=255)
    phone: str | None = Field(None, min_length=10, max_length=20)
    business_name: str | None = Field(None, min_length=2, max_length=255)
    is_active: bool | None = None

    @model_validator(mode="after")
    def at_least_one_field(self) -> "UpdateLandlordRequest":
        values = [self.full_name, self.phone, self.business_name, self.is_active]
        if all(v is None for v in values):
            raise ValueError("At least one field must be provided")
        return self


# building
class CreateBuildingRequest(BaseModel):
    name: str = Field(min_length=2, max_length=255)
    address: str = Field(min_length=5, max_length=500)
    city: str = Field(min_length=2, max_length=100)
    code: str = Field(
        min_length=2,
        max_length=10,
        pattern=r"^[A-Z0-9]+$",
        description="Uppercase alphanumeric e.g. PALM",
    )
    garbage_charge: Decimal = Field(default=Decimal("500.00"), ge=0)
    water_rate_per_unit: Decimal = Field(
        gt=0,
        description="KES per cubic metre",
    )


class BuildingResponse(BaseModel):
    id: uuid.UUID
    landlord_id: uuid.UUID
    name: str
    address: str
    city: str
    code: str
    created_at: datetime
    model_config = {"from_attributes": True}


class BuildingDetailResponse(BuildingResponse):
    water_rate_per_unit: Decimal
    garbage_charge: Decimal
    total_units: int
    occupied_units: int


class PaginatedResponse(BaseModel):
    items: list[Any]
    total: int
    page: int
    page_size: int


# unit
class CreateUnitRequest(BaseModel):
    unit_number: str = Field(min_length=1, max_length=20)
    floor: int | None = Field(None, ge=0)
    rent_amount: Decimal = Field(gt=0)

    @field_validator("unit_number")
    @classmethod
    def strip_unit_number(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("unit_number cannot be blank")
        return v.upper()  # normalize to uppercase to match account_reference format


class UnitResponse(BaseModel):
    id: uuid.UUID
    building_id: uuid.UUID
    unit_number: str
    floor: int | None
    rent_amount: Decimal
    status: str
    created_at: datetime
    model_config = {"from_attributes": True}


class UpdateUnitRequest(BaseModel):
    rent_amount: Decimal | None = Field(None, gt=0)
    floor: int | None = None


# Tenant
class CreateTenantRequest(BaseModel):
    full_name: str = Field(min_length=2, max_length=255)
    phone: str = Field(min_length=10, max_length=20)
    national_id: str = Field(min_length=6, max_length=30)
    email: EmailStr | None = None

    @field_validator("phone")
    @classmethod
    def normalise_phone(cls, v: str) -> str:
        v = v.strip().replace(" ", "").replace("-", "").replace("+", "")
        if v.startswith("0") and len(v) == 10:
            v = "254" + v[1:]
        return v


class TenantResponse(BaseModel):
    id: uuid.UUID
    landlord_id: uuid.UUID
    full_name: str
    phone: str
    national_id: str
    email: str | None
    created_at: datetime
    model_config = {"from_attributes": True}


# lease
class CreateLeaseRequest(BaseModel):
    tenant_id: uuid.UUID
    deposit_amount: Decimal = Field(gt=0)
    start_date: date
    end_date: date | None = None
    initial_water_reading: Decimal = Field(
        ge=0,
        description="Opening meter reading for this tenant — required on first lease",
    )


class LeaseResponse(BaseModel):
    id: uuid.UUID
    unit_id: uuid.UUID
    tenant_id: uuid.UUID
    rent_amount: Decimal
    deposit_amount: Decimal
    deposit_status: str
    start_date: date
    end_date: date | None
    account_reference: str
    status: str
    created_at: datetime
    model_config = {"from_attributes": True}


# water readings


class CreateWaterReadingsRequest(BaseModel):
    current_reading: Decimal = Field(ge=0)
    period: str = Field(
        pattern=r"^\d{4}-\d{2}$",
        description="YYYY-MM e.g. 2025-01",
    )

    @field_validator("period")
    @classmethod
    def validate_period(cls, v: str) -> str:
        year, month = v.split("-")
        if not (1 <= int(month) <= 12):
            raise ValueError("period month must be between 01 and 12")
        return v


class WaterReadingsResponse(BaseModel):
    id: uuid.UUID
    unit_id: uuid.UUID
    period: str
    previous_reading: Decimal
    current_reading: Decimal
    units_consumed: Decimal
    rate_per_unit: Decimal
    water_charge: Decimal
    entered_at: datetime
    model_config = {"from_attributes": True}


# ledger
class LedgerEntryResponse(BaseModel):
    id: uuid.UUID
    lease_id: uuid.UUID
    period: str
    base_rent: Decimal
    water_charge: Decimal
    garbage_charge: Decimal
    previous_balance: Decimal
    total_amount_due: Decimal
    amount_paid: Decimal
    balance: Decimal
    status: str
    water_reading_entered: bool
    model_config = {"from_attributes": True}


# payments
class PaymentResponse(BaseModel):
    id: uuid.UUID
    landlord_id: uuid.UUID
    mpesa_receipt_number: str
    account_reference: str
    msisdn: str
    amount: Decimal
    transaction_date: datetime
    matched_lease_id: uuid.UUID | None
    matched_period: str | None
    is_reconciled: bool
    model_config = {"from_attributes": True}


class ManualMatchRequest(BaseModel):
    lease_id: uuid.UUID
    period: str = Field(pattern=r"^\d{4}-\d{2}$")


class PaymentListResponse(BaseModel):
    items: list[PaymentResponse]
    total: int
    page: int
    page_size: int


# Reports


class DefaulterResponse(BaseModel):
    lease_id: uuid.UUID
    unit_number: str
    building_name: str
    tenant_name: str
    tenant_phone: str
    account_reference: str
    period: str
    total_amount_due: Decimal
    amount_paid: Decimal
    balance: Decimal
    status: str


class OccupancyResponse(BaseModel):
    building_id: uuid.UUID
    building_name: str
    total_units: int
    occupied: int
    vacant: int
    occupancy_rate: float


class RevenueResponse(BaseModel):
    period: str
    expected_revenue: Decimal
    collected_revenue: Decimal
    outstanding: Decimal
    collection_rate: float
